CREATE DATABASE IF NOT EXISTS psc_case001 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS psc_case002 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS psc_case003 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

GRANT ALL PRIVILEGES ON psc_case001.* TO 'psc'@'%';
GRANT ALL PRIVILEGES ON psc_case002.* TO 'psc'@'%';
GRANT ALL PRIVILEGES ON psc_case003.* TO 'psc'@'%';

FLUSH PRIVILEGES;
